Logic Puzzle: There are two ducks in front of a duck, two ducks behind a duck and a duck in the middle. How many ducks are there?
Answer: Three. Two ducks are in front of the last duck; the first duck has two ducks behind; one duck is between the other two. 
Logic Puzzle: Five people were eating apples, A finished before B, but behind C. D finished before E, but behind B. What was the finishing order?
Answer: CABDE. Putting the first three in order, A finished in front of B but behind C, so CAB. Then, we know D finished before B, so CABD. We know E finished after D, so CABDE.
Logic Puzzle: Jack is looking at Anne. Anne is looking at George. Jack is married, George is not, and we don’t know if Anne is married. Is a married person looking at an unmarried person?
Answer: Yes. If Anne is married, then she is married and looking at George, who is unmarried. If Anne is unmarried, then Jack, who is married, is looking at her. Either way, the statement is correct.
Logic Puzzle: A man has 53 socks in his drawer: 21 identical blue, 15 identical black and 17 identical red. The lights are out and he is completely in the dark. How many socks must he take out to make 100 percent certain he has at least one pair of black socks?
Answer: 40 socks. If he takes out 38 socks (adding the two biggest amounts, 21 and 17), although it is very unlikely, it is possible they could all be blue and red. To make 100 percent certain that he also has a pair of black socks he must take out a further two socks.
Logic Puzzle: The day before two days after the day before tomorrow is Saturday. What day is it today?
Answer: Friday. The “day before tomorrow” is today; “the day before two days after” is really one day after. So if “one day after today is Saturday,” then it must be Friday.
Logic Puzzle: This “burning rope” problem is a classic logic puzzle. You have two ropes that each take an hour to burn, but burn at inconsistent rates. How can you measure 45 minutes? (You can light one or both ropes at one or both ends at the same time.)
Answer: Because they both burn inconsistently, you can’t just light one end of a rope and wait until it’s 75 percent of the way through. But, this is what you can do: Light the first rope at both ends, and light the other rope at one end, all at the same time. The first rope will take 30 minutes to burn (even if one side burns faster than the other, it still takes 30 minutes). The moment the first rope goes out, light the other end of the second rope. Because the time elapsed of the second rope burning was 30 minutes, the remaining rope will also take 30 minutes; lighting it from both ends will cut that in half to 15 minutes, giving you 45 minutes all together.
Lying or telling the truth logic puzzles
Logic Puzzle: You’re at a fork in the road in which one direction leads to the City of Lies (where everyone always lies) and the other to the City of Truth (where everyone always tells the truth). There’s a person at the fork who lives in one of the cities, but you’re not sure which one. What question could you ask the person to find out which road leads to the City of Truth?
Answer: “Which direction do you live?” Someone from the City of Lies will lie and point to the City of Truth; someone from the City of Truth would tell the truth and also point to the City of Truth.
Logic Puzzle: A girl meets a lion and unicorn in the forest. The lion lies every Monday, Tuesday and Wednesday and the other days he speaks the truth. The unicorn lies on Thursdays, Fridays and Saturdays, and the other days of the week he speaks the truth. “Yesterday I was lying,” the lion told the girl. “So was I,” said the unicorn. What day is it?
Answer: Thursday. The only day they both tell the truth is Sunday; but today can’t be Sunday because the lion also tells the truth on Saturday (yesterday). Going day by day, the only day one of them is lying and one of them is telling the truth with those two statements is Thursday.
Logic Puzzle: There are three people (Alex, Ben and Cody), one of whom is a knight, one a knave, and one a spy. The knight always tells the truth, the knave always lies, and the spy can either lie or tell the truth. Alex says: “Cody is a knave.” Ben says: “Alex is a knight.” Cody says: “I am the spy.” Who is the knight, who the knave, and who the spy?
Answer: We know Ben isn’t telling the truth, because if he was, there would be two knights; so Ben could be either the knave or the spy. Cody also can’t be the knight, because then his statement would be a lie. So that must mean Alex is the knight. Ben, therefore, must be the spy, since the spy sometimes tells the truth; leaving Cody as the knave.
River crossing logic puzzles
Logic Puzzle: A farmer wants to cross a river and take with him a wolf, a goat and a cabbage. He has a boat, but it can only fit himself plus either the wolf, the goat or the cabbage. If the wolf and the goat are alone on one shore, the wolf will eat the goat. If the goat and the cabbage are alone on the shore, the goat will eat the cabbage. How can the farmer bring the wolf, the goat and the cabbage across the river without anything being eaten?
Answer: First, the farmer takes the goat across. The farmer returns alone and then takes the wolf across, but returns with the goat. Then the farmer takes the cabbage across, leaving it with the wolf and returning alone to get the goat.
Logic Puzzle: Let’s pretend we’re on the metric system and use kilograms instead of pounds to give us a starting base number of 100. Four people (Alex, Brook, Chris and Dusty) want to cross a river in a boat that can only carry 100kg. Alex weighs 90kg, Brook weighs 80kg, Chris weighs 60kg and Dusty weighs 40kg, and they have 20kg of supplies. How do they get across?
Answer: There may be a couple variations that will work, but here’s one way: Chris and Dusty row across (combined 100kg), Dusty returns. Alex rows over, and Chris returns. Chris and Dusty row across again, Dusty returns. Brook rows across with the supplies (combined 100kg), and Chris returns. Chris and Dusty row across again.
Logic Puzzle: This famous river crossing problem is known as the “bridge and torch” puzzle. Four people are crossing a bridge at night, so they all need a torch—but they just have one that only lasts 15 minutes. Alice can cross in one minute, Ben in two minutes, Cindy in five minutes and Don in eight minutes. No more than two people can cross at a time; and when two cross, they have to go at the slower person’s pace. How do they get across in 15 minutes?
Answer: Alice and Ben cross first in two minutes, and Alice crosses back alone with the torch in one minute. Then the two slowest people, Cindy and Don, cross in eight minutes. Ben returns in two minutes, and Alice and Ben return in two minutes. They just made it in 15 minutes exactly.
Deadly choices logic puzzles
Logic Puzzle: A bad guy is playing Russian roulette with a six-shooter revolver. He puts in one bullet, spins the chambers and fires at you, but no bullet comes out. He gives you the choice of whether or not he should spin the chambers again before firing a second time. Should he spin again?
Answer: Yes. Before he spins, there’s a one in six chance of a bullet being fired. After he spins, one of those chances has been taken away, leaving a one in five chance and making it more likely a bullet will be fired. Best to spin again.
Logic Puzzle: Same situation, but two bullets are put in consecutive chambers. Should you tell the bad guy to spin the chambers again?
Answer: No. With two bullets, you have a two chances in six (or one in three) to get hit with a bullet before he fires the first time. Because we know the previous round was one of four empty chambers, that leaves four positions the gun could now be in, with only one followed by a bullet; therefore leaving you with a one in four chance the second round will fire. Since one in four is better odds than one in three, he shouldn’t spin again. 
Logic Puzzle: This one could also fall in the lying/truth category. A man is caught on the king’s property. He is brought before the king to be punished. The king says, “You must give me a statement. If it is true, you will be killed by lions. If it is false, you will be killed by trampling of wild buffalo. If I can’t figure it out, I’ll have to let you go.” Sure enough, the man was released. What was the man’s statement?
Answer: “I will be killed by trampling of wild buffalo.” This stumped the king because if it’s true, he’ll be killed by lions, which would render the statement not true. If it’s a lie, he’d be killed by wild buffalo, which would make it a truth. Since the king had no solution, he had to let the man go.
Harder Logic Puzzles
Logic Puzzle: Susan and Lisa decided to play tennis against each other. They bet $1 on each game they played. Susan won three bets and Lisa won $5. How many games did they play?
Answer: Eleven. Because Lisa lost three games to Susan, she had lost $3 ($1 per game). So, she had to win back that $3 with three more games, then win another five games to win $5.   
Logic Puzzle: If five cats can catch five mice in five minutes, how long will it take one cat to catch one mouse?
Answer: Five minutes. Using the information we know, it would take one cat 25 minutes to catch all five mice (5×5=25). Then working backward and dividing 25 by five, we get five minutes for one cat to catch each mouse.
Logic Puzzle: There is a barrel with no lid and some wine in it. “This barrel of wine is more than half full,” says the woman. “No, it’s not,” says the man. “It’s less than half full.” Without any measuring implements and without removing any wine from the barrel, how can they easily determine who is correct?
Answer: Tilt the barrel until the wine barely touches the lip of the barrel. If the bottom of the barrel is visible then it is less than half full. If the barrel bottom is still completely covered by the wine, then it is more than half full.
Logic Puzzle: There are three bags, each containing two marbles. Bag A contains two white marbles, Bag B contains two black marbles, and Bag C contains one white marble and one black marble. You pick a random bag and take out one marble, which is white. What is the probability that the remaining marble from the same bag is also white?
Answer: 2 out of 3. You know you don’t have Bag B. But because Bag A has two white marbles, you could have picked either marble; if you think of it as four marbles in total from Bags A and C, three white and one black, you’ll have a greater chance of picking another white marble.
Logic Puzzle: Three men are lined up behind each other. The tallest man is in the back and can see the heads of the two in front of him; the middle man can see the one man in front of him; the man in front can’t see anyone. They are blindfolded and hats are placed on their heads, picked from three black hats and two white hats. The extra two hats are hidden and the blindfolds removed. The tallest man is asked if he knows what color hat he’s wearing; he doesn’t. The middle man is asked if he knows; he doesn’t. But the man in front, who can’t see anyone, says he knows. How does he know, and what color hat is he wearing?
Answer: Black. The man in front knew he and the middle man aren’t both wearing white hats or the man in the back would have known he had a black hat (since there are only two white hats). The man in front also knows the middle man didn’t see him with a white hat because if he did, based on the tallest man’s answer, the middle man would have known he himself was wearing a black hat. So, the man in front knows his hat must be black.
Logic Puzzle: There are three crates, one with apples, one with oranges, and one with both apples and oranges mixed. Each crate is closed and labeled with one of three labels: Apples, Oranges, or Apples and Oranges. The label maker broke and labeled all of the crates incorrectly. How could you pick just one fruit from one crate to figure out what’s in each crate?
Answer: Pick a fruit from the crate marked Apples and Oranges. If that fruit is an apple, you know that the crate should be labeled Apples because all of the labels are incorrect as they are. Therefore, you know the crate marked Apples must be Oranges (if it were labeled Apples and Oranges, the Oranges crate would be labeled correctly, and we know it isn’t), and the one marked Oranges is Apples and Oranges. Alternately, if you picked an orange from the crate marked Apples and Oranges, you know that crate should be marked Oranges, the one marked Oranges must be Apples, and the one marked Apples must be Apples and Oranges.

Hardest Logic Puzzles
Logic Puzzle: A teacher writes six words on a board: “cat dog has max dim tag.” She gives three students, Albert, Bernard and Cheryl each a piece of paper with one letter from one of the words. Then she asks, “Albert, do you know the word?” Albert immediately replies yes. She asks, “Bernard, do you know the word?” He thinks for a moment and replies yes. Then she asks Cheryl the same question. She thinks and then replies yes. What is the word?
Answer: Dog. Albert knows right away because he has one of the unique letters that only appear once in all the words: c o h s x i. So, we know the word is not “tag.” All of these unique letters appear in different words, except for “h” and “s” in “has,” and Bernard can figure out what the word is from the unique letters that are left: t, g, h, s. This eliminates “max” and “dim.” Cheryl can then narrow it down the same way. Because there is only one unique letter left, the letter “d,” the word must be “dog.” (For more on this answer, watch the video below.)


// Write a function that converts above data to string
// Separate by the comma
//Convert to Object
//Insert inside of an array